GET http://localhost:3003/

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test1",
  "author": "Test1",
  "url": "Test1",
  "likes": 0
}

###
GET http://localhost:3003/api/blogs