###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test1",
  "author": "Test1",
  "url": "Test1",
  "likes": 0
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/6429369e2492477b4282f414

###
PUT http://localhost:3003/api/blogs/642930791cfb7ce687b6451c
Content-Type: application/json

{
  "title": "Test1",
  "author": "Test1",
  "url": "Test1",
  "likes": 0
}