version: '3.8'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app-frontend
      - app-backend
    container_name: todo-nginx-dev

  app-frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: ./dev.Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
      - PORT=3000
    volumes:
      - ./todo-frontend/:/usr/src/app
    container_name: todo-frontend-dev

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: todo-mongo-dev

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: todo-redis-dev

  app-backend:
    image: todo-backend-dev
    build:
      context: ./todo-backend
      dockerfile: ./dev.Dockerfile
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://the_username:the_password@todo-mongo-dev:27017/the_database
      - REDIS_URL=redis://todo-redis-dev:6379
    volumes:
      - ./todo-backend/:/usr/src/app
    depends_on:
      - mongo
      - redis
    container_name: todo-backend-dev