version: '3.8'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - app-frontend
      - app-backend
    container_name: todo-nginx-prod

  app-frontend:
    image: todo-frontend-prod
    build:
      context: ./todo-frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080/api/
      - PORT=3000
    container_name: todo-frontend-prod

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: todo-mongo-prod

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: todo-redis-prod

  app-backend:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - MONGO_URL=mongodb://the_username:the_password@todo-mongo-prod:27017/the_database
      - REDIS_URL=redis://todo-redis-prod:6379
    depends_on:
      - mongo
      - redis
    container_name: todo-backend-prod