DELETE http://localhost:3001/api/people/4

###
POST http://localhost:3001/api/people
content-type: application/json

{
  "name": "John Doe",
  "number": 30
}

###
POST http://localhost:3001/api/people